import random
print("Let's play a number guessing game: \n")
print("How game works:\n\nEnter the starting & ending integer and guess the number between them which is generated by computer ")


def guess():
    x = int(input("\nenter the first integer from where you want to start: "))
    y = int(input("enter the second integer where you want to end: "))

    random_number = random.randint(x, y)

    guess = 0
    while guess != random_number:

        guess = int(input(f"\nguess the number between {x} - {y}: "))
        if guess in range(x, y+1):
            if guess > random_number:
                print("Hint :number is smaller then you guessed")

            elif guess < random_number:
                print("Hint :number is greater then you guessed")

            elif guess == random_number:
                print("\nhey! You guessed correct number :) ")

        else:
            print(f"\n\"guess the number between {x} - {y}\"")


guess()
